### ISSUE TITLE
Issue in accelerometer_example.py

### ISSUE THREAD

**Issue by FarnooshHeidari** [rymc/bHealth#20]
In accelerometer_example.py when using the provided example dataset:

https://github.com/rymc/bHealth/blob/858df1a1ce2a10c6267699a5511e3d403d1f9360/examples/accelerometer_example.py#L51-L58

I get an error of out of bound access. The error might occur in transform.slide(), where "windowed_raw" is first assigned the value and then its "current_position" goes forward:

https://github.com/rymc/bHealth/blob/858df1a1ce2a10c6267699a5511e3d403d1f9360/bhealth/transforms.py#L402-L411

**Comment by perellonieto** [comment]
Thanks for pointing out the issue. It is possible that during commit 16a2bfa8d0a1465d011b550cf0d9857a9761d0ce I broke the function to move the window. I will need to check, as the transform class previously expected a window_overlap parameter, but I think the name of the parameter was misleading.

I think I will change the parameter to stride, and adjust the rest of the code accordingly.

I still need to reproduce the error, but what I mentioned needs to be sorted out.

**Comment by FarnooshHeidari** [comment]
Thanks for your reply.

By the way, the array out of bound is caught in an exception.

**Comment by perellonieto** [comment]
I have run the example and when the warning is captured this is the output message

```
index 72800 is out of bounds for axis 0 with size 72766
```

**Comment by perellonieto** [comment]
I just realised that the example code uses the exception to stop the sliding window. This is therfore intentionally for the correct functioning of the transformation. This needs clearly to be addressed in Issue #21

Meanwhile, it would be advisable to check if the sliding window is out of bounds, instead of relying in a raised exception.
